/detector_carril:
  ros__parameters:
    ancho_bot: 600
    ancho_carril_px: 350
    ancho_top: 120
    corte_y_pct: 55
    h_max: 179
    h_min: 0
    s_max: 60
    s_min: 0
    start_type_description_service: true
    suavizado_pct: 20
    use_sim_time: false
    v_max: 255
    v_min: 150

